language: python
python:
  - "2.7"

os:
  - linux

before_install:
  - sudo apt-get install python-opengl
  - sudo apt-get install python-pygame

install:
  - pip install -r requirements.txt

script: 
  - cd source
  - py.test
