language: python
python:
  - "2.7"

os:
  - linux

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install python-pygame

install:
  - pip install -r requirements.txt

script: 
  - cd source
  - py.test
